import createClient, { type Middleware } from "openapi-fetch";
import useAuthStore from "../composables/store/useAuthStore";
import {
	ForbiddenError,
	SystemError,
	UnAuthError,
	AppServerError,
} from "../types/error";
import type { paths } from "./types/schema"; // generated by openapi-typescript

const myMiddleware: Middleware = {
	onRequest({ request, options }) {
		const authStore = useAuthStore();
		request.headers.set("Authorization", authStore.get());
		return request;
	},
	onResponse({ request, response, options }) {
		const { body, ...resOptions } = response;
		if (response.status >= 400 && response.status < 500) {
			if (response.status === 401) {
				handleAuthError(response);
			} else if (response.status === 403) {
				handleForbiddenError(response);
			} else {
				handleSystemError(response);
			}
		} else if (response.status >= 500) {
			handleBusinessError(response);
		} else {
			return response;
		}
	},
	async onError({ error }) {
		// wrap errors thrown by fetch
		console.error(error);
		return;
	},
};

const client = createClient<paths>({
	baseUrl: `http://localhost:${import.meta.env.VITE_BACKEND_PORT}/`,
	querySerializer: {
		object: {
			style: "form",
			explode: true,
		},
	},
});

// register middleware
client.use(myMiddleware);

const handleAuthError = (response: Response) => {
	throw new UnAuthError(response.status);
};

const handleForbiddenError = (response: Response) => {
	throw new ForbiddenError(response.status);
};

const handleSystemError = (response: Response) => {
	throw new SystemError(response.status);
};

const handleBusinessError = (response: Response) => {
	throw new AppServerError(response);
};

export default client;
